project:
  type: website
  pre-render: src/R/combine-data-tables.R

website:
  title: "USDA SEP Fellows R Workshop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - basic.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
